### ISSUE TITLE
复现问题

### ISSUE THREAD

**Issue by QWERTY0205** [GeoX-Lab/LSTTN#3]
想请问一下这个gpu数量应该怎么调整，没发现有控制这个的参数呢

**Comment by Juuzoufan** [comment]
main.py里面的--gpus以及forecasting.py的GPU_NUM

**Comment by Juuzoufan** [comment]
> 想请问一下这个gpu数量应该怎么调整，没发现有控制这个的参数呢

main.py里面的--gpus以及forecasting.py的GPU_NUM

**Comment by QWERTY0205** [comment]
哦哦哦 看到了 谢谢您！

**Comment by Juuzoufan** [comment]
> 哦哦哦 看到了 谢谢您！

我最近也在学习这篇，可以互相交流一下。
